/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SceneSceneIdRouteImport } from './routes/scene/$sceneId'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as SceneSceneIdIndexRouteImport } from './routes/scene/$sceneId/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as SceneSceneIdImagesIndexRouteImport } from './routes/scene/$sceneId/images/index'
import { Route as SceneSceneIdImagesImageIdRouteImport } from './routes/scene/$sceneId/images/$imageId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneSceneIdRoute = SceneSceneIdRouteImport.update({
  id: '/scene/$sceneId',
  path: '/scene/$sceneId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneSceneIdIndexRoute = SceneSceneIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SceneSceneIdRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const SceneSceneIdImagesIndexRoute = SceneSceneIdImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => SceneSceneIdRoute,
} as any)
const SceneSceneIdImagesImageIdRoute =
  SceneSceneIdImagesImageIdRouteImport.update({
    id: '/images/$imageId',
    path: '/images/$imageId',
    getParentRoute: () => SceneSceneIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/scene/$sceneId': typeof SceneSceneIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/scene/$sceneId/': typeof SceneSceneIdIndexRoute
  '/scene/$sceneId/images/$imageId': typeof SceneSceneIdImagesImageIdRoute
  '/scene/$sceneId/images/': typeof SceneSceneIdImagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/scene/$sceneId': typeof SceneSceneIdIndexRoute
  '/scene/$sceneId/images/$imageId': typeof SceneSceneIdImagesImageIdRoute
  '/scene/$sceneId/images': typeof SceneSceneIdImagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/scene/$sceneId': typeof SceneSceneIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/scene/$sceneId/': typeof SceneSceneIdIndexRoute
  '/scene/$sceneId/images/$imageId': typeof SceneSceneIdImagesImageIdRoute
  '/scene/$sceneId/images/': typeof SceneSceneIdImagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/settings'
    | '/project/$projectId'
    | '/scene/$sceneId'
    | '/project/$projectId/'
    | '/scene/$sceneId/'
    | '/scene/$sceneId/images/$imageId'
    | '/scene/$sceneId/images/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/settings'
    | '/project/$projectId'
    | '/scene/$sceneId'
    | '/scene/$sceneId/images/$imageId'
    | '/scene/$sceneId/images'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/settings'
    | '/project/$projectId'
    | '/scene/$sceneId'
    | '/project/$projectId/'
    | '/scene/$sceneId/'
    | '/scene/$sceneId/images/$imageId'
    | '/scene/$sceneId/images/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SettingsRoute: typeof SettingsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  SceneSceneIdRoute: typeof SceneSceneIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$sceneId': {
      id: '/scene/$sceneId'
      path: '/scene/$sceneId'
      fullPath: '/scene/$sceneId'
      preLoaderRoute: typeof SceneSceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$sceneId/': {
      id: '/scene/$sceneId/'
      path: '/'
      fullPath: '/scene/$sceneId/'
      preLoaderRoute: typeof SceneSceneIdIndexRouteImport
      parentRoute: typeof SceneSceneIdRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/scene/$sceneId/images/': {
      id: '/scene/$sceneId/images/'
      path: '/images'
      fullPath: '/scene/$sceneId/images/'
      preLoaderRoute: typeof SceneSceneIdImagesIndexRouteImport
      parentRoute: typeof SceneSceneIdRoute
    }
    '/scene/$sceneId/images/$imageId': {
      id: '/scene/$sceneId/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/scene/$sceneId/images/$imageId'
      preLoaderRoute: typeof SceneSceneIdImagesImageIdRouteImport
      parentRoute: typeof SceneSceneIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

interface SceneSceneIdRouteChildren {
  SceneSceneIdIndexRoute: typeof SceneSceneIdIndexRoute
  SceneSceneIdImagesImageIdRoute: typeof SceneSceneIdImagesImageIdRoute
  SceneSceneIdImagesIndexRoute: typeof SceneSceneIdImagesIndexRoute
}

const SceneSceneIdRouteChildren: SceneSceneIdRouteChildren = {
  SceneSceneIdIndexRoute: SceneSceneIdIndexRoute,
  SceneSceneIdImagesImageIdRoute: SceneSceneIdImagesImageIdRoute,
  SceneSceneIdImagesIndexRoute: SceneSceneIdImagesIndexRoute,
}

const SceneSceneIdRouteWithChildren = SceneSceneIdRoute._addFileChildren(
  SceneSceneIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  SettingsRoute: SettingsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  SceneSceneIdRoute: SceneSceneIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
